"""Application constants"""

# HTTP Status Codes
HTTP_200_OK = 200
HTTP_201_CREATED = 201
HTTP_400_BAD_REQUEST = 400
HTTP_404_NOT_FOUND = 404
HTTP_422_UNPROCESSABLE_ENTITY = 422
HTTP_500_INTERNAL_SERVER_ERROR = 500

# Error Codes
ERROR_CODE_ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND"
ERROR_CODE_INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
ERROR_CODE_INVALID_AMOUNT = "INVALID_AMOUNT"
ERROR_CODE_VALIDATION_ERROR = "VALIDATION_ERROR"
ERROR_CODE_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

# Business Rules
MAX_DECIMAL_PLACES = 2
MIN_BALANCE = 0
MIN_TRANSFER_AMOUNT = 0
